### PR TITLE
feature: custom infoboxes and pushpin icons

### PR DESCRIPTION
**Pull request by marcelusaurelius**

### CODE REVIEW

**Comment by TopsyCM** [comment]
The custom info boxes added are rather specific changes for a library like this. Will other users want or need such a feature?

**Comment by marcelusaurelius** [comment]
> The custom info boxes added are rather specific changes for a library like this. Will other users want or need such a feature?


unlikely

**Comment by TopsyCM** [comment]
Then we probably shouldn't add these changes to this repo unless they can be made generic.

**Comment by psheraton** [comment]
As discussed via Slack, these changes need to be moved into our private repo with configuration based changes made here.

**Pull request closed without merging**
